site_name: HTML Tab Plugin for DITA-OT
repo_url: 'https://github.com/jason-fox/fox.jason.tabs.css'
repo_name: GitHub
pages:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
theme: readthedocs
extra_css:
  - 'https://jason-fox.github.io/fox.jason.tabs.css/dita.css'
